/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface WishData {
  firstPulls: [
    (
      | []
      | [number]
      | [number, string]
      | [number, string, string]
      | [number, string, string, number]
      | [number, string, string, number, boolean]
      | [number, string, string, number, boolean, boolean]
      | [number, string, string, number, boolean, boolean, number]
    ),
    (
      | []
      | [number]
      | [number, string]
      | [number, string, string]
      | [number, string, string, number]
      | [number, string, string, number, boolean]
      | [number, string, string, number, boolean, boolean]
      | [number, string, string, number, boolean, boolean, number]
    ),
    (
      | []
      | [number]
      | [number, string]
      | [number, string, string]
      | [number, string, string, number]
      | [number, string, string, number, boolean]
      | [number, string, string, number, boolean, boolean]
      | [number, string, string, number, boolean, boolean, number]
    ),
    (
      | []
      | [number]
      | [number, string]
      | [number, string, string]
      | [number, string, string, number]
      | [number, string, string, number, boolean]
      | [number, string, string, number, boolean, boolean]
      | [number, string, string, number, boolean, boolean, number]
    ),
    (
      | []
      | [number]
      | [number, string]
      | [number, string, string]
      | [number, string, string, number]
      | [number, string, string, number, boolean]
      | [number, string, string, number, boolean, boolean]
      | [number, string, string, number, boolean, boolean, number]
    ),
    ...Array<| []
    | [number]
    | [number, string]
    | [number, string, string]
    | [number, string, string, number]
    | [number, string, string, number, boolean]
    | [number, string, string, number, boolean, boolean]
    | [number, string, string, number, boolean, boolean, number]>
  ];
  legendaryPulls:
  | []
  | [number]
  | [number, string]
  | [number, string, 'character' | 'weapon']
  | [number, string, 'character' | 'weapon', number]
  | [number, string, 'character' | 'weapon', number, boolean]
  | [number, string, 'character' | 'weapon', number, boolean, boolean]
  | Array<[number, string, 'character' | 'weapon', number, boolean, boolean, number]>;
  rarePulls: [number, number, number, number, number, number, number, number, number, number];
  banner: number;
  total: number;
  legendary: number;
  rare: number;
  lastPull?: {
    time: number;
    id: string;
  };
}
