/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface WishTotalData {
  type: 'beginners' | 'standard' | 'character-event' | 'weapon-event';
  uid: string;
  total: number;
  legendary: number;
  rare: number;
  rateOffLegendary?: {
    win: number;
    lose: number;
    maxStreak: number;
    currentStreak: number;
  };
  rateOffRare?: {
    win: number;
    lose: number;
    maxStreak: number;
    currentStreak: number;
  };
}
