/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface WishData {
  firstPulls: [
    (
      | []
      | [number]
      | [number, string]
      | [number, string, string]
      | [number, string, string, number]
      | [number, string, string, number, boolean]
    ),
    (
      | []
      | [number]
      | [number, string]
      | [number, string, string]
      | [number, string, string, number]
      | [number, string, string, number, boolean]
    ),
    (
      | []
      | [number]
      | [number, string]
      | [number, string, string]
      | [number, string, string, number]
      | [number, string, string, number, boolean]
    ),
    (
      | []
      | [number]
      | [number, string]
      | [number, string, string]
      | [number, string, string, number]
      | [number, string, string, number, boolean]
    ),
    (
      | []
      | [number]
      | [number, string]
      | [number, string, string]
      | [number, string, string, number]
      | [number, string, string, number, boolean]
    ),
    ...(
      | []
      | [number]
      | [number, string]
      | [number, string, string]
      | [number, string, string, number]
      | [number, string, string, number, boolean]
    )[]
  ];
  legendaryPulls:
    | []
    | [number]
    | [number, string]
    | [number, string, "character" | "weapon"]
    | [number, string, "character" | "weapon", number]
    | [number, string, "character" | "weapon", number, boolean][];
  rarePulls: [number, number, number, number, number, number, number, number, number, number];
  banner: number;
  total: number;
  legendary: number;
  rare: number;
}
